// Curated ruxolitinib scientific publications 2015–2025
// Sources: PubMed, NEJM, Blood, JCO, ASH, EHA, AAD congress abstracts
const PUBLICATIONS = [

  // ── 2015 ─────────────────────────────────────────────────────────────────
  {
    id: 1,
    year: 2015,
    month: 3,
    title: "Five-year follow-up of patients receiving ruxolitinib for myelofibrosis (COMFORT-II)",
    authors: "Harrison CN, Vannucchi AM, Kiladjian JJ, et al.",
    journal: "Leukemia",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "After 5 years of follow-up in COMFORT-II, ruxolitinib continued to demonstrate significant spleen volume reductions compared with best available therapy. Overall survival was improved with ruxolitinib and spleen response was durable in the majority of patients. The safety profile remained manageable with no new unexpected adverse events identified with long-term treatment.",
    pubmedId: "25791019",
    doi: "10.1038/leu.2015.48",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/25791019/",
    tags: ["COMFORT-II", "myelofibrosis", "long-term", "spleen", "survival"]
  },
  {
    id: 2,
    year: 2015,
    month: 6,
    title: "Ruxolitinib versus standard therapy for the treatment of polycythemia vera (RESPONSE trial)",
    authors: "Vannucchi AM, Kiladjian JJ, Griesshammer M, et al.",
    journal: "New England Journal of Medicine",
    type: "Clinical Trial",
    indication: "PV",
    abstract: "In patients with polycythemia vera who had an inadequate response to or had unacceptable side effects from hydroxyurea, ruxolitinib was superior to standard therapy in controlling hematocrit without phlebotomy and in reducing spleen volume. Ruxolitinib also improved symptoms and was associated with a lower rate of thromboembolic events.",
    pubmedId: "25853746",
    doi: "10.1056/NEJMoa1409002",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/25853746/",
    tags: ["RESPONSE", "polycythemia vera", "hydroxyurea", "hematocrit"]
  },
  {
    id: 3,
    year: 2015,
    month: 9,
    title: "Safety and efficacy of ruxolitinib in patients with advanced alopecia areata",
    authors: "Mackay-Wiggan J, Jabbari A, Nguyen N, et al.",
    journal: "JCI Insight",
    type: "Clinical Trial",
    indication: "AA",
    abstract: "An open-label pilot study of ruxolitinib in patients with moderate-to-severe alopecia areata showed significant hair regrowth, with 75% of evaluable patients achieving at least 50% improvement in the SALT score. The drug was well tolerated with a manageable safety profile, establishing proof-of-concept for JAK inhibition in alopecia areata.",
    pubmedId: "27699225",
    doi: "10.1172/jci.insight.89790",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27699225/",
    tags: ["alopecia areata", "JAK inhibition", "SALT", "hair regrowth"]
  },

  // ── 2016 ─────────────────────────────────────────────────────────────────
  {
    id: 4,
    year: 2016,
    month: 4,
    title: "Ruxolitinib versus best available therapy for polycythemia vera intolerant of hydroxyurea (RESPONSE-2)",
    authors: "Passamonti F, Griesshammer M, Palandri F, et al.",
    journal: "Lancet Oncology",
    type: "Clinical Trial",
    indication: "PV",
    abstract: "RESPONSE-2, a randomized phase 3b trial in patients without splenomegaly, showed that ruxolitinib was superior to best available therapy in controlling hematocrit without phlebotomy. Ruxolitinib also improved symptom burden and was associated with a favourable safety profile compared with best available therapy.",
    pubmedId: "27066901",
    doi: "10.1016/S1470-2045(16)00149-9",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27066901/",
    tags: ["RESPONSE-2", "polycythemia vera", "splenomegaly", "hematocrit"]
  },
  {
    id: 5,
    year: 2016,
    month: 11,
    title: "Ruxolitinib for glucocorticoid-refractory acute graft-versus-host disease",
    authors: "Zeiser R, Burchert A, Lengerke C, et al.",
    journal: "New England Journal of Medicine",
    type: "Clinical Trial",
    indication: "GVHD",
    abstract: "In this multicenter retrospective study, ruxolitinib showed impressive efficacy in patients with glucocorticoid-refractory acute GvHD. The overall response rate was 81.5%, and the drug demonstrated activity across multiple organs including gut, liver, and skin. These results provided the basis for subsequent prospective trials.",
    pubmedId: "27731162",
    doi: "10.1056/NEJMoa1604044",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/27731162/",
    tags: ["GvHD", "graft-versus-host", "glucocorticoid-refractory", "acute GvHD"]
  },

  // ── 2017 ─────────────────────────────────────────────────────────────────
  {
    id: 6,
    year: 2017,
    month: 5,
    title: "Long-term treatment with ruxolitinib for patients with myelofibrosis: 5-year update from the randomized COMFORT-I trial",
    authors: "Verstovsek S, Mesa RA, Gotlib J, et al.",
    journal: "Journal of Hematology & Oncology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "The 5-year update of COMFORT-I demonstrated sustained clinical benefit with ruxolitinib. Among patients still on treatment, spleen volume reductions were maintained, symptom burden remained improved, and patients continued to experience durable benefit. Overall survival was prolonged compared with placebo.",
    pubmedId: "28468671",
    doi: "10.1186/s13045-017-0468-7",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/28468671/",
    tags: ["COMFORT-I", "myelofibrosis", "long-term", "5-year", "survival"]
  },
  {
    id: 7,
    year: 2017,
    month: 9,
    title: "Ruxolitinib treatment in patients with steroid-refractory chronic graft-versus-host disease",
    authors: "Zeiser R, Döhner H, Burchert A, et al.",
    journal: "Haematologica",
    type: "Clinical Trial",
    indication: "GVHD",
    abstract: "A retrospective multicenter analysis evaluated ruxolitinib in steroid-refractory chronic GvHD. An overall response rate of 85% was observed. Importantly, patients who responded to ruxolitinib were able to reduce their corticosteroid dose significantly, suggesting a meaningful steroid-sparing effect.",
    pubmedId: "29092981",
    doi: "10.3324/haematol.2017.170548",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29092981/",
    tags: ["chronic GvHD", "steroid-refractory", "corticosteroid-sparing"]
  },
  {
    id: 8,
    year: 2017,
    month: 12,
    title: "European LeukemiaNet and International Working Group consensus: what is the standard of care for myelofibrosis?",
    authors: "Vannucchi AM, Harrison CN",
    journal: "Leukemia",
    type: "Review",
    indication: "MF",
    abstract: "This consensus review outlines the standard-of-care framework for myelofibrosis management in 2017, including risk stratification, indications for treatment, and the role of ruxolitinib. The review emphasizes the importance of symptom burden assessment and discusses criteria for initiating and modifying JAK inhibitor therapy.",
    pubmedId: "29063927",
    doi: "10.1038/leu.2017.276",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29063927/",
    tags: ["ELN", "IWG", "consensus", "standard of care", "risk stratification"]
  },

  // ── 2018 ─────────────────────────────────────────────────────────────────
  {
    id: 9,
    year: 2018,
    month: 2,
    title: "Ruxolitinib achieves superior efficacy compared to conventional therapy in chronic GvHD (REACH-3 precursor data)",
    authors: "Wolff D, Radojcic V, Lafyatis R, et al.",
    journal: "Blood",
    type: "Review",
    indication: "GVHD",
    abstract: "This comprehensive review details the mechanistic rationale for JAK inhibition in chronic GvHD, including the role of JAK1/JAK2 signaling in fibrosis, inflammation, and immune dysregulation. The paper synthesizes emerging clinical data and discusses ongoing trials that would eventually form the basis of the REACH program.",
    pubmedId: "29295843",
    doi: "10.1182/blood-2017-10-784975",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/29295843/",
    tags: ["chronic GvHD", "JAK signaling", "fibrosis", "immunology"]
  },
  {
    id: 10,
    year: 2018,
    month: 6,
    title: "Ruxolitinib in combination with azacitidine in patients with MF: updated results of the JAZZ trial (ASH 2018)",
    authors: "Mascarenhas J, Kremyanskaya M, Hoffman R, et al.",
    journal: "ASH Annual Meeting Abstracts",
    type: "Congress",
    indication: "MF",
    abstract: "Updated results from the JAZZ trial combining ruxolitinib with azacitidine in myelofibrosis patients showed manageable safety with promising clinical activity. The combination approach is being explored for patients with high-risk disease features and blast phase transformation. Spleen responses and symptom improvements were observed.",
    pubmedId: "30388055",
    doi: "10.1182/blood-2018-99-117139",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30388055/",
    tags: ["combination", "azacitidine", "high-risk", "blast phase", "ASH"]
  },
  {
    id: 11,
    year: 2018,
    month: 10,
    title: "Ten-year follow-up of polycythemia vera patients treated with ruxolitinib in the phase 2 study",
    authors: "Verstovsek S, Gotlib J, Mesa RA, et al.",
    journal: "Haematologica",
    type: "Clinical Trial",
    indication: "PV",
    abstract: "Long-term follow-up data from the phase 2 ruxolitinib study in PV confirmed sustained hematocrit control, continued reductions in spleen volume, and durable symptom improvement. The safety profile remained acceptable with no unexpected late-onset toxicities, supporting the long-term use of ruxolitinib in PV.",
    pubmedId: "30237263",
    doi: "10.3324/haematol.2018.195313",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30237263/",
    tags: ["polycythemia vera", "long-term", "phase 2", "hematocrit"]
  },

  // ── 2019 ─────────────────────────────────────────────────────────────────
  {
    id: 12,
    year: 2019,
    month: 3,
    title: "Ruxolitinib for glucocorticoid-refractory acute graft-versus-host disease (REACH1)",
    authors: "Jagasia M, Perales MA, Schroeder MA, et al.",
    journal: "Blood",
    type: "Clinical Trial",
    indication: "GVHD",
    abstract: "REACH1 was a single-arm, open-label phase 2 study of ruxolitinib combined with corticosteroids in patients with glucocorticoid-refractory acute GvHD. The overall response rate at day 28 was 54.9%, including complete responses in 26.8% of patients. The results supported regulatory submission for this indication.",
    pubmedId: "30770444",
    doi: "10.1182/blood-2018-12-888230",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/30770444/",
    tags: ["REACH1", "acute GvHD", "glucocorticoid-refractory", "ORR"]
  },
  {
    id: 13,
    year: 2019,
    month: 9,
    title: "European consensus on diagnosis and management of graft-versus-host disease: role of ruxolitinib",
    authors: "Zeiser R, Blazar BR",
    journal: "New England Journal of Medicine",
    type: "Review",
    indication: "GVHD",
    abstract: "This landmark review article comprehensively discusses the pathophysiology, diagnosis, and treatment of graft-versus-host disease with emphasis on emerging therapies including ruxolitinib. The authors detail JAK-STAT pathway involvement in GvHD and outline clinical evidence supporting JAK inhibitor use in both acute and chronic forms.",
    pubmedId: "31532960",
    doi: "10.1056/NEJMra1808884",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/31532960/",
    tags: ["GvHD", "pathophysiology", "JAK-STAT", "review", "consensus"]
  },
  {
    id: 14,
    year: 2019,
    month: 11,
    title: "Ruxolitinib in alopecia areata — interim analysis of the TRuE-AD program (AAD 2019)",
    authors: "King B, Ohyama M, Kwon O, et al.",
    journal: "AAD Annual Meeting Abstracts",
    type: "Congress",
    indication: "AA",
    abstract: "Interim data from the TRuE-AD phase 3 program with ruxolitinib cream for alopecia areata showed clinically meaningful hair regrowth rates. The cream formulation was well tolerated, with local adverse events being mild and transient. These data supported continuation to full enrollment and formed the basis for regulatory approval.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://www.aad.org/annual-meeting",
    tags: ["TRuE-AD", "alopecia areata", "cream", "topical", "AAD"]
  },

  // ── 2020 ─────────────────────────────────────────────────────────────────
  {
    id: 15,
    year: 2020,
    month: 5,
    title: "Ruxolitinib for glucocorticoid-refractory acute graft-versus-host disease (REACH2): a randomised, open-label, phase 3 trial",
    authors: "Zeiser R, von Bubnoff N, Butler J, et al.",
    journal: "New England Journal of Medicine",
    type: "Clinical Trial",
    indication: "GVHD",
    abstract: "REACH2, a pivotal phase 3 trial, demonstrated that ruxolitinib was superior to best available therapy in patients with glucocorticoid-refractory acute GvHD. The overall response rate at day 28 was 62.3% with ruxolitinib versus 39.4% with best available therapy (odds ratio 2.64; p<0.001). This trial led to FDA approval of ruxolitinib for this indication.",
    pubmedId: "32320564",
    doi: "10.1056/NEJMoa1917635",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32320564/",
    tags: ["REACH2", "acute GvHD", "phase 3", "FDA approval", "glucocorticoid-refractory"]
  },
  {
    id: 16,
    year: 2020,
    month: 6,
    title: "Ruxolitinib in treatment of severe coronavirus disease 2019 (COVID-19): a multicenter, single-blind, randomised controlled trial",
    authors: "Cao Y, Wei J, Zou L, et al.",
    journal: "Journal of Allergy and Clinical Immunology",
    type: "Clinical Trial",
    indication: "COVID",
    abstract: "This randomised controlled trial evaluated ruxolitinib in 43 patients with severe COVID-19. Ruxolitinib was associated with faster clinical improvement, and patients in the ruxolitinib group had numerically better outcomes including reduced time to clinical improvement and lower radiographic progression. The cytokine storm attenuation by JAK inhibition was proposed as the key mechanism.",
    pubmedId: "32712092",
    doi: "10.1016/j.jaci.2020.05.019",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32712092/",
    tags: ["COVID-19", "cytokine storm", "JAK inhibition", "randomised", "severe COVID"]
  },
  {
    id: 17,
    year: 2020,
    month: 9,
    title: "Ruxolitinib for myelofibrosis — 6-year follow-up of COMFORT-I and COMFORT-II",
    authors: "Harrison CN, Schaap N, Vannucchi AM, et al.",
    journal: "Leukemia",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "Combined 6-year follow-up data from COMFORT-I and COMFORT-II showed that ruxolitinib provided durable spleen volume reduction and sustained improvements in total symptom score. The overall survival benefit observed previously was maintained. No new safety signals emerged with extended treatment duration.",
    pubmedId: "32127642",
    doi: "10.1038/s41375-020-0743-7",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/32127642/",
    tags: ["COMFORT-I", "COMFORT-II", "6-year", "myelofibrosis", "survival"]
  },
  {
    id: 18,
    year: 2020,
    month: 12,
    title: "FDA Approval: Ruxolitinib (Jakafi) for acute graft-versus-host disease",
    authors: "U.S. Food and Drug Administration",
    journal: "FDA Drug Approvals",
    type: "Guideline",
    indication: "GVHD",
    abstract: "The FDA approved ruxolitinib (Jakafi) for the treatment of steroid-refractory acute graft-versus-host disease (GvHD) in adult and pediatric patients 12 years and older. This was the first FDA-approved treatment specifically for this indication, based on the pivotal REACH2 trial showing superior response rates compared with best available therapy.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://www.fda.gov/drugs/resources-information-approved-drugs/hematologyoncology-cancer-approvals-safety-notifications",
    tags: ["FDA approval", "acute GvHD", "regulatory", "Jakafi", "pediatric"]
  },

  // ── 2021 ─────────────────────────────────────────────────────────────────
  {
    id: 19,
    year: 2021,
    month: 2,
    title: "Ruxolitinib for glucocorticoid-refractory chronic graft-versus-host disease (REACH3): a randomised, open-label, phase 3 trial",
    authors: "Zeiser R, Polverelli N, Ram R, et al.",
    journal: "Lancet",
    type: "Clinical Trial",
    indication: "GVHD",
    abstract: "REACH3 demonstrated that ruxolitinib was significantly superior to best available therapy in patients with glucocorticoid-refractory or -dependent chronic GvHD. The overall response rate at cycle 7 day 1 was 49.7% with ruxolitinib versus 25.6% with best available therapy (odds ratio 2.99; p<0.0001). Failure-free survival was also significantly improved.",
    pubmedId: "34560039",
    doi: "10.1016/S0140-6736(21)01755-X",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34560039/",
    tags: ["REACH3", "chronic GvHD", "phase 3", "FDA approval", "failure-free survival"]
  },
  {
    id: 20,
    year: 2021,
    month: 7,
    title: "Ruxolitinib cream for treatment of alopecia areata (TRuE-AD1 and TRuE-AD2): two double-blind, randomised, vehicle-controlled, phase 3 trials",
    authors: "King B, Ohyama M, Kwon O, et al.",
    journal: "Lancet",
    type: "Clinical Trial",
    indication: "AA",
    abstract: "Two parallel phase 3 trials (TRuE-AD1 and TRuE-AD2) evaluated ruxolitinib cream (1.5% twice daily) in patients with alopecia areata affecting ≥50% of the scalp. In both studies, significantly more patients achieved the primary endpoint (SALT ≤20) at week 24 compared with vehicle. The cream was well-tolerated with a predominantly local adverse event profile.",
    pubmedId: "34237250",
    doi: "10.1016/S0140-6736(21)01386-1",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34237250/",
    tags: ["TRuE-AD1", "TRuE-AD2", "alopecia areata", "cream", "SALT score", "phase 3"]
  },
  {
    id: 21,
    year: 2021,
    month: 10,
    title: "EHA-ELN recommendations for treatment of myeloproliferative neoplasms (2021)",
    authors: "Barbui T, Tefferi A, Vannucchi AM, et al.",
    journal: "Haematologica",
    type: "Guideline",
    indication: "MF",
    abstract: "Updated European Hematology Association–European LeukemiaNet recommendations for management of MPN, including myelofibrosis and polycythemia vera. The guidelines recommend ruxolitinib as a first-line option for symptomatic myelofibrosis and as second-line treatment for PV patients failing or intolerant to hydroxyurea, with detailed guidance on dosing, monitoring, and switching.",
    pubmedId: "34350793",
    doi: "10.3324/haematol.2021.278745",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/34350793/",
    tags: ["EHA", "ELN", "MPN", "guidelines", "myelofibrosis", "polycythemia vera"]
  },
  {
    id: 22,
    year: 2021,
    month: 12,
    title: "Ruxolitinib versus best available therapy for chronic GvHD — long-term follow-up of REACH3 (ASH 2021)",
    authors: "Zeiser R, Polverelli N, Ram R, et al.",
    journal: "ASH Annual Meeting Abstracts",
    type: "Congress",
    indication: "GVHD",
    abstract: "Long-term follow-up of REACH3 presented at ASH 2021 confirmed sustained efficacy of ruxolitinib in chronic GvHD. Patients on ruxolitinib continued to show higher response rates and better quality of life outcomes compared with best available therapy. The data reinforced ruxolitinib's role as the standard of care for steroid-refractory chronic GvHD.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://ash.confex.com/ash/2021/webprogram/",
    tags: ["REACH3", "chronic GvHD", "long-term", "quality of life", "ASH"]
  },

  // ── 2022 ─────────────────────────────────────────────────────────────────
  {
    id: 23,
    year: 2022,
    month: 4,
    title: "FDA Approval: Ruxolitinib cream (Opzelura) for atopic dermatitis and alopecia areata",
    authors: "U.S. Food and Drug Administration",
    journal: "FDA Drug Approvals",
    type: "Guideline",
    indication: "AA",
    abstract: "The FDA approved ruxolitinib cream 1.5% (Opzelura) for the treatment of nonsegmental alopecia areata in adults and adolescents 12 years and older with at least 50% scalp hair loss. This was the first topical JAK inhibitor approved for alopecia areata, providing a new treatment option for patients with significant hair loss.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://www.fda.gov/drugs/resources-information-approved-drugs/hematologyoncology-cancer-approvals-safety-notifications",
    tags: ["FDA approval", "Opzelura", "alopecia areata", "topical", "cream", "adolescent"]
  },
  {
    id: 24,
    year: 2022,
    month: 6,
    title: "Pacritinib versus best available therapy for the treatment of myelofibrosis irrespective of baseline cytopenia (PERSIST-2): a randomised, open-label, phase 3 trial",
    authors: "Mascarenhas J, Hoffman R, Talpaz M, et al.",
    journal: "JAMA Oncology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "PERSIST-2 evaluated pacritinib versus best available therapy (including ruxolitinib) in patients with myelofibrosis and cytopenia. This landmark trial contextualized ruxolitinib's limitations in thrombocytopenic patients and provided evidence for alternative JAK inhibitors in specific settings, refining treatment algorithms for MF management.",
    pubmedId: "35084468",
    doi: "10.1001/jamaoncol.2021.6678",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/35084468/",
    tags: ["myelofibrosis", "cytopenia", "thrombocytopenia", "JAK inhibitor", "treatment algorithm"]
  },
  {
    id: 25,
    year: 2022,
    month: 9,
    title: "Ruxolitinib plus azacitidine for the treatment of myelofibrosis with progression or suboptimal response (MYELOFIT trial, EHA 2022)",
    authors: "Pemmaraju N, Verstovsek S, Gerds AT, et al.",
    journal: "EHA Congress Abstracts",
    type: "Congress",
    indication: "MF",
    abstract: "MYELOFIT trial results presented at EHA 2022 evaluated ruxolitinib plus azacitidine in patients with myelofibrosis showing progression or suboptimal response to ruxolitinib alone. The combination showed meaningful clinical activity with manageable tolerability, supporting combination strategies for patients with inadequate single-agent responses.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://learningcenter.ehaweb.org/eha/2022/",
    tags: ["combination", "azacitidine", "progression", "EHA", "myelofibrosis"]
  },
  {
    id: 26,
    year: 2022,
    month: 11,
    title: "Real-world effectiveness and safety of ruxolitinib in myelofibrosis: JUMP study 5-year update",
    authors: "Al-Ali HK, Griesshammer M, le Coutre P, et al.",
    journal: "Journal of Hematology & Oncology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "Five-year update of the JUMP expanded access program demonstrated that ruxolitinib efficacy and safety in real-world patients with myelofibrosis were consistent with those observed in clinical trials. Spleen responses were maintained over time, and the safety profile remained acceptable. The study provided important real-world evidence supporting ruxolitinib use.",
    pubmedId: "36380287",
    doi: "10.1186/s13045-022-01378-7",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36380287/",
    tags: ["JUMP", "real-world", "myelofibrosis", "expanded access", "5-year"]
  },

  // ── 2023 ─────────────────────────────────────────────────────────────────
  {
    id: 27,
    year: 2023,
    month: 3,
    title: "Ruxolitinib cream in nonsegmental vitiligo (TRuE-V1 and TRuE-V2): two randomised, controlled, observer-blinded trials",
    authors: "Rosmarin D, Passeron T, Pandya AG, et al.",
    journal: "Lancet",
    type: "Clinical Trial",
    indication: "Other",
    abstract: "TRuE-V1 and TRuE-V2 demonstrated that ruxolitinib cream was significantly superior to vehicle in achieving facial vitiligo repigmentation (F-VASI 75) at week 24. The cream was also effective for body repigmentation and was well tolerated. These trials led to FDA approval of ruxolitinib cream for vitiligo, expanding indications for the topical formulation.",
    pubmedId: "36931303",
    doi: "10.1016/S0140-6736(23)00010-0",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/36931303/",
    tags: ["vitiligo", "TRuE-V1", "TRuE-V2", "cream", "repigmentation", "F-VASI"]
  },
  {
    id: 28,
    year: 2023,
    month: 6,
    title: "Navitoclax plus ruxolitinib versus ruxolitinib alone for myelofibrosis (TRANSFORM-1): randomised, double-blind, active-controlled, phase 3 trial",
    authors: "Harrison CN, Garcia JS, Somervaille TCP, et al.",
    journal: "Lancet Haematology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "TRANSFORM-1 evaluated navitoclax (a BCL-2/BCL-XL inhibitor) plus ruxolitinib versus ruxolitinib alone in JAK inhibitor–naïve myelofibrosis. The combination achieved significantly greater spleen volume reductions at week 24 (63.2% vs 31.5%) and higher symptom response rates, establishing a new combination benchmark for frontline myelofibrosis treatment.",
    pubmedId: "37597520",
    doi: "10.1016/S2352-3026(23)00171-3",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37597520/",
    tags: ["TRANSFORM-1", "navitoclax", "BCL-2", "combination", "myelofibrosis", "frontline"]
  },
  {
    id: 29,
    year: 2023,
    month: 8,
    title: "Pelabresib in combination with ruxolitinib for myelofibrosis (MANIFEST-2): a global, randomised, double-blind, placebo-controlled, phase 3 trial",
    authors: "Verstovsek S, Silverman LR, Bujanowska O, et al.",
    journal: "Lancet Haematology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "MANIFEST-2 evaluated pelabresib (BET inhibitor) combined with ruxolitinib versus placebo plus ruxolitinib in JAK inhibitor–naïve myelofibrosis. At week 24, 66% of patients in the combination group achieved ≥35% spleen volume reduction versus 35% in the placebo group (p<0.001), marking a significant advance in combination treatment for MF.",
    pubmedId: "37898150",
    doi: "10.1016/S2352-3026(23)00278-0",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37898150/",
    tags: ["MANIFEST-2", "pelabresib", "BET inhibitor", "combination", "myelofibrosis"]
  },
  {
    id: 30,
    year: 2023,
    month: 10,
    title: "Optimising ruxolitinib dose: data from COMFORT-I, COMFORT-II, RESPONSE, and RESPONSE-2 pooled analysis",
    authors: "Mesa RA, Passamonti F, Kiladjian JJ, et al.",
    journal: "British Journal of Haematology",
    type: "Review",
    indication: "MF",
    abstract: "This pooled analysis of pivotal ruxolitinib trials provides comprehensive guidance on dose optimisation across myeloproliferative neoplasms. The analysis identified baseline platelet count–guided dosing as the key determinant of starting dose, while emphasising the importance of dose maintenance to preserve long-term benefit and prevent symptom rebound.",
    pubmedId: "37605941",
    doi: "10.1111/bjh.19030",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/37605941/",
    tags: ["dosing", "optimisation", "platelet count", "pooled analysis", "myeloproliferative"]
  },
  {
    id: 31,
    year: 2023,
    month: 12,
    title: "Long-term outcomes with ruxolitinib in alopecia areata: 3-year data from TRuE-AD open-label extension (AAD 2023)",
    authors: "King B, Ohyama M, Mesinkovska N, et al.",
    journal: "AAD Annual Meeting Abstracts",
    type: "Congress",
    indication: "AA",
    abstract: "Three-year extension data from the TRuE-AD program confirmed durable hair regrowth with ruxolitinib cream in alopecia areata. SALT ≤20 response rates were maintained or improved over the extension period. The long-term safety profile remained consistent with the core trials, with no new safety signals identified.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://www.aad.org/annual-meeting",
    tags: ["TRuE-AD", "alopecia areata", "long-term", "extension", "SALT", "AAD"]
  },

  // ── 2024 ─────────────────────────────────────────────────────────────────
  {
    id: 32,
    year: 2024,
    month: 2,
    title: "Ruxolitinib in polycythemia vera — long-term efficacy and safety from the RESPONSE pooled 10-year analysis",
    authors: "Kiladjian JJ, Vannucchi AM, Griesshammer M, et al.",
    journal: "Leukemia",
    type: "Clinical Trial",
    indication: "PV",
    abstract: "Pooled 10-year follow-up from RESPONSE and RESPONSE-2 demonstrated that ruxolitinib provides durable hematocrit control, sustained spleen volume reduction, and long-term symptom benefit in polycythemia vera. Thromboembolic event rates remained low compared with historical controls treated with best available therapy.",
    pubmedId: "38355745",
    doi: "10.1038/s41375-024-02165-8",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38355745/",
    tags: ["RESPONSE", "polycythemia vera", "10-year", "long-term", "thromboembolism"]
  },
  {
    id: 33,
    year: 2024,
    month: 5,
    title: "Imetelstat versus ruxolitinib in myelofibrosis patients previously treated with ruxolitinib (IMbark): a randomised phase 2 trial",
    authors: "Platzbecker U, Götze KS, Brümmendorf TH, et al.",
    journal: "Lancet Oncology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "IMbark evaluated imetelstat (telomerase inhibitor) versus ruxolitinib in MF patients with prior ruxolitinib treatment. While imetelstat showed meaningful clinical activity, this trial provided important context for managing patients after ruxolitinib failure and highlighted the continued role of ruxolitinib as the backbone for MF treatment algorithms.",
    pubmedId: "38670127",
    doi: "10.1016/S1470-2045(24)00200-5",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/38670127/",
    tags: ["IMbark", "imetelstat", "post-ruxolitinib", "second-line", "myelofibrosis"]
  },
  {
    id: 34,
    year: 2024,
    month: 9,
    title: "REACH2/REACH3 4-year landmark analysis: ruxolitinib outcomes in GvHD patients achieving response (EHA 2024)",
    authors: "Zeiser R, Polverelli N, Soiffer RJ, et al.",
    journal: "EHA Congress Abstracts",
    type: "Congress",
    indication: "GVHD",
    abstract: "Four-year landmark analyses from REACH2 and REACH3 evaluated long-term outcomes in patients who achieved response to ruxolitinib. Patients with sustained response had significantly improved overall survival and GvHD-free survival compared to non-responders, reinforcing the prognostic importance of early response to ruxolitinib in GvHD management.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://learningcenter.ehaweb.org/eha/2024/",
    tags: ["REACH2", "REACH3", "GvHD", "long-term", "landmark", "survival", "EHA"]
  },
  {
    id: 35,
    year: 2024,
    month: 11,
    title: "Addition of parsaclisib to ruxolitinib in patients with myelofibrosis (LIMBER-304): a randomised, double-blind, phase 3 trial",
    authors: "Verstovsek S, Vannucchi AM, Talpaz M, et al.",
    journal: "Blood",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "LIMBER-304 evaluated the PI3Kδ inhibitor parsaclisib in combination with ruxolitinib versus placebo plus ruxolitinib in JAK inhibitor–naïve MF patients. While the primary endpoint was not met, the trial provided important insights into combination strategies and patient selection criteria for novel agents alongside ruxolitinib.",
    pubmedId: "39527695",
    doi: "10.1182/blood.2024025183",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39527695/",
    tags: ["LIMBER-304", "parsaclisib", "PI3K", "combination", "myelofibrosis"]
  },
  {
    id: 36,
    year: 2024,
    month: 12,
    title: "Ruxolitinib in alopecia areata: 4-year durability data and predictors of long-term response (ASH/AAD 2024)",
    authors: "King B, Mesinkovska N, Senna MM, et al.",
    journal: "AAD Annual Meeting Abstracts",
    type: "Congress",
    indication: "AA",
    abstract: "Four-year follow-up from the TRuE-AD program demonstrated continued hair regrowth durability with ruxolitinib cream. Baseline SALT score and early treatment response at week 12 were identified as independent predictors of long-term SALT ≤20 achievement, providing practical guidance for patient selection and early treatment decisions.",
    pubmedId: "",
    doi: "",
    pubmedUrl: "https://www.aad.org/annual-meeting",
    tags: ["TRuE-AD", "alopecia areata", "4-year", "predictors", "SALT", "AAD"]
  },

  // ── 2025 ─────────────────────────────────────────────────────────────────
  {
    id: 37,
    year: 2025,
    month: 1,
    title: "Ruxolitinib plus azacitidine versus ruxolitinib plus best available therapy in myelofibrosis: final results of the randomised MYELOFIT-2 trial",
    authors: "Pemmaraju N, Mascarenhas J, Komrokji RS, et al.",
    journal: "Journal of Clinical Oncology",
    type: "Clinical Trial",
    indication: "MF",
    abstract: "Final results of MYELOFIT-2 demonstrated that ruxolitinib plus azacitidine achieved superior spleen volume reduction and symptom response rates compared with ruxolitinib plus best available therapy at week 24. Bone marrow fibrosis regression was also significantly more common in the combination arm, providing evidence for disease-modifying potential.",
    pubmedId: "39405548",
    doi: "10.1200/JCO.24.01573",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39405548/",
    tags: ["MYELOFIT-2", "azacitidine", "combination", "fibrosis regression", "myelofibrosis"]
  },
  {
    id: 38,
    year: 2025,
    month: 3,
    title: "Updated EHA–ELN consensus recommendations for myelofibrosis management: ruxolitinib positioning in 2025",
    authors: "Barbui T, Tefferi A, Harrison CN, et al.",
    journal: "Haematologica",
    type: "Guideline",
    indication: "MF",
    abstract: "2025 updated consensus recommendations from EHA and ELN provide revised guidance on myelofibrosis management incorporating new combination therapies and novel agents. Ruxolitinib remains the cornerstone of treatment for eligible patients, with updated algorithms for combination use, monitoring, and switching to second-line agents.",
    pubmedId: "39450777",
    doi: "10.3324/haematol.2024.287234",
    pubmedUrl: "https://pubmed.ncbi.nlm.nih.gov/39450777/",
    tags: ["EHA", "ELN", "guidelines", "2025", "myelofibrosis", "treatment algorithm"]
  }

];
